# Generated by Django 5.1.2 on 2024-10-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../learning_logs/static/learning_logs/profile_images/default.jpg', upload_to='../learning_logs/static/learning_logs/profile_images/'),
        ),
    ]
